apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-svc.name" . }}-pdb
spec:
  minAvailable: 2
  selector:
    app.kubernetes.io/name: {{ include "hello-svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
